name: Automate Issues
on:
  issues:
    types: [opened]
jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Print Data
        run: echo "${{toJson(github)}}"
